### ISSUE TITLE
redirection to the admin

### ISSUE THREAD

**Issue by AndreaCrotti** [munhitsu/django-dowser#9] opened 2014-10-17 14:03 UTC
Hi and thanks for the very nice project, I was trying to use it though but no luck so far, using Django 1.4.13.

I followed the instructions but every time I go to 
http://localhost:8000/dowser/

my browser redirects automatically to (even after I'm logged in as admin):

http://localhost:8000/adminiu0Roojo/?next=/dowser/

I've also seen an error once

    Traceback (most recent call last):
      File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/Users/andrea/.virtualenvs/depop_backend/lib/python2.7/site-packages/django_dowser/__init__.py", line 37, in start
        self.tick()
      File "/Users/andrea/.virtualenvs/depop_backend/lib/python2.7/site-packages/django_dowser/__init__.py", line 47, in tick
        typename = objtype.__module__ + "." + objtype.__name__
    TypeError: unsupported operand type(s) for +: 'property' and 'str'

Which I guess depends on some unhandled type and I thought that this was the issue maybe, it still doesn't work even if I handle the exception.

Any ideas? Thanks

**Comment by munhitsu** [comment] 2015-06-19 14:20
@AndreaCrotti I'm closing the issue as I can't reproduce it and there is no update from you. Keep us posted if you have any further problems with it.

**Closed by munhitsu** 2015-06-19 14:20 UTC
